"on":
  push:
    branches:
      - global
name: "[global] Deploy Live Captions Global 🚀🌎"
jobs:
  us-central:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: Deploy stack
        timeout-minutes: 30
        run: exec porter apply -f ./porter.yaml
        env:
          PORTER_APP_NAME: live-captions-global
          PORTER_NAMESPACE: prod
          NODE_ENV: production
          PORTER_CLUSTER: "4689"
          PORTER_DEPLOYMENT_TARGET_ID: 4a24a192-04c8-421f-8fc2-22db1714fdc0
          PORTER_HOST: https://dashboard.porter.run
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_PROJECT: "15081"
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4689 }}

  us-west:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: 4965
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 15081
        PORTER_APP_NAME: live-captions-global
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4965 }}
        PORTER_DEPLOYMENT_TARGET_ID: 540690ee-b1d7-4a5e-80e9-683d11001c75

  us-east:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: 4977
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 15081
        PORTER_APP_NAME: live-captions-global
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4977 }}
        PORTER_DEPLOYMENT_TARGET_ID: 2b421266-64ab-46d4-bf29-55b3223392ee

  east-asia:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: 4754
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 15081
        PORTER_APP_NAME: live-captions-global
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4754 }}
        PORTER_DEPLOYMENT_TARGET_ID: 7ed60823-5c81-40a8-8162-95cb0e1e1480

  france:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: 4696
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 15081
        PORTER_APP_NAME: live-captions-global
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4696 }}
        PORTER_DEPLOYMENT_TARGET_ID: 6d7f479b-fd7e-4f5d-83ad-154edc538012

  australia-east:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: 4978
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 15081
        PORTER_APP_NAME: live-captions-global
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4978 }}
        PORTER_DEPLOYMENT_TARGET_ID: 1978d230-f754-46c4-8aa7-cd7950a6b52e

  canada-central:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: 4753
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 15081
        PORTER_APP_NAME: live-captions-global
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_APP_15081_4753 }}
        PORTER_DEPLOYMENT_TARGET_ID: 8ce84edb-7609-4ce5-906f-373f4783ef93

